### ISSUE TITLE
pid.h usage on spin examples

### ISSUE THREAD

**Issue by luizvilla** [owntech-foundation/examples#8]
**Description**

SPIN examples call the `pid.h` library which requires a manual action from the user to uncomment a line on platformio.ini. 

We would like to avoid this action so that new users can easily get to know the technology with a maximum of automatic actions.

**Solution** 

As of now, the easiest solution to this issue is to remote any reference to the control library from the SPIN examples.

**Comment by rrodgeur** [comment]
commit has been merged, then we close the issue.
